eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8788
  
spring:
  application:
    name: tcloud-user-hi
  aop:
    auto: true
    proxy-target-class: true