eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
  
spring:
  application:
    name: tcloud-user-account
  aop:
    auto: true
    proxy-target-class: true
  datasource:
      url: jdbc:mysql://localhost:3306/svw_account?useUnicode=true
#     url: jdbc:h2:mem:test
      driver-class-name: com.mysql.jdbc.Driver
#     driver-class-name: org.h2.Driver
      username: root
      password: root
#     password: 123456

#     启动初始化创建schema的脚本
#     schema: classpath:db/schema.sql
#     启动时初始化数据的脚本 
#     data: classpath:db/data.sql 
      
      hikari:
        maximumPoolSize: 10
      
mybatis:                               
  mapperLocations: classpath*:META-INF/com/svw/tbox/tcloud/user/account/mapper/*.xml
  type-aliases-package: com.svw.tbox.tcloud.user.account.entity
mapper:
  mappers: 
    - tk.mybatis.mapper.common.Mapper
  not-empty: false
  mapper.identity: MYSQL
  
pagehelper:
  helperDialect: mySql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

feign:
  hystrix: 
    enabled: true
    
logging.level:
  com.svw.tbox.tcloud.user.account.dao: debug